### ISSUE TITLE
Calling malloc/free should be done by scheduler

### ISSUE THREAD

**Issue by khalkash** [JonNRb/gthread#15]
void * mymalloc(size_t size, gthread_task_t* owner);
void myfree(void * data, gthread_task_t* owner);
Both of these need to be invoked by scheduler to indicate the calling thread. Currently, I am not sure as to what the best way to do this is (what files need to be changed) so if one of you guys with more knowledge of the scheduler code could do it, that would be cool.

**Comment by JonNRb** [comment]
I'll take a look at this. There's one or two places where the scheduler uses libc malloc() and free() and I want to get rid of those as well. I know the assignment description says there should be an indication for mymalloc()s done by the scheduler and "kernel" but I think we can get rid of these and only have mymalloc() used by user code.
