### ISSUE TITLE
Implement memory protection

### ISSUE THREAD

**Issue by khalkash** [JonNRb/gthread#17]
Need a way to protect memory for part B. The section of memory in need of protect is &myblock[0] to the address in which the metadata starts (which can be found by using the function getMetaStart(); (see mymalloc.h header). If sigsev occurs, simply check which which thread is causing it, call "int placePagesContig(gthread_task_t* owner);" which will find the pages allocated to the thread and swap them into to &myblock[0] contiguously.  This function returns n, the number of pages swapped in, as well so you can lift protection for from the start of the array to (char*)&myblock[0] + n*page_size.

Main code is a bit buggy right now but this can be done in parallel while I fix.

**Comment by JonNRb** [comment]
I'll take a look at this

**Comment by khalkash** [comment]
Update: think the recent push I did, the malloc/free call works fine and has swap file implementation. Only issue left is I need to clear unused pages when a pointer is freed. So it should be easier to use. Let me know if you have any questions about the code if you need anything. :D
